name: Go CI-backend

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    name: Validate code
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Check formatting
        run: |
          files="$(gofmt -l .)"

          if [ -n "$files" ]; then
            echo "These files are not formatted:"
            echo "$files"
            gofmt -d .
            exit 1
          fi

      - name: Check go.mod and go.sum
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run go vet
        run: go vet ./...

  test:
    name: Run tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -race -cover ./...

      - name: Build project
        run: go build ./...
      
